swagger: '2.0'
info:
  title: D-BAS API
  description: Access argumentation logic
  version: "1.0.0"
host: localhost:4284
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Test connection
      description:
        Verify that the API can be reached.
      tags:
        - general
      responses:
        '200':
          description: Say hello to the user
          schema:
            $ref: '#/definitions/hello'
  /login:
    post:
      summary: Login user
      description:
        Makes an API call to the selected D-BAS instance. A user account has to be present on this instance.
      tags:
        - auth
      parameters:
        - name: login
          in: body
          required: true
          schema:
            $ref: '#/definitions/login'
      responses:
        '200':
          description: Login with credentials
          schema:
            $ref: '#/definitions/loginResponse'
        default:
          description: User could not be authenticated
          schema:
            $ref: '#/definitions/defaultError'

definitions:
  hello:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
  login:
    type: object
    properties:
      nickname:
        type: string
      password:
        type: string
    required:
      - nickname
      - password
  loginResponse:
    type: object
    properties:
      token:
        type: string
  defaultError:
    type: object
    properties:
      status:
        type: string
      errors:
        type: string