version: 2
jobs:
  build:
#    working_directory: ~/cci-demo-clojure
    docker:
      - image: clojure:alpine
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run: bin/lein do test, uberjar
